[package]
name = "pulsejet-rs"
license = "MIT"
version = "0.1.0"
edition = "2021"
exclude = ["roundtrip"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
